version: '3.8'

services:
  app:
    build: .
    container_name: population_report_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=world
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: population_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
    ports:
      - "3301:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
      # Add SQL initialization file if it exists
      - ./Database/world.sql:/docker-entrypoint-initdb.d/world.sql

networks:
  app_network:

volumes:
  db_data: