version: '3.8'

services:
  app:
    build: .
    container_name: population_report_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: population_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Root password for MySQL
      MYSQL_DATABASE: world      # Name of the database to create
    ports:
      - "3301:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:

volumes:
  db_data:
